[tool.poetry]
name = "dbtc-metadata-api"
version = "0.1.0"
description = "Python interface to the dbt Cloud metadata API"
authors = ["Doug Guthrie <douglas.p.guthrie@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
sgqlc = "^15.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
